### ISSUE TITLE
쓰담 BE sprint 2 todo list

### ISSUE THREAD

**Issue by sooani** [codestates-seb/abc02_002#3]
# **sprint 2 (~23.01.10 ) 배포테스트전 까지 할일✨**

-  **도메인 기능 ( CRUD )** 🛠
   ----
- [x] 회원관리 - 회원 가입, 조회, _(수정, 탈퇴)_
- [x] 모임관리 - 모임 생성, 조회, _(수정, 삭제)_ 
- [x] 댓글관리 - 댓글 작성, _(수정, 삭제)_

--------
##  그외 필수완성은 아니지만 중간중간 체크해야 할 일
-  **공통 기능** 🚨
   ----
- [x] 예외처리
- [ ] 보안 - 로그인기능(로그인!!!!)
- [ ] JPA
- [x] 유틸리티
- [ ] API 문서화
