### ISSUE TITLE
쓰담 FE sprint 3 todo list

### ISSUE THREAD

**Issue by hyehye225** [codestates-seb/abc02_002#54]
### 회원 관리

- [ ] 리덕스로 로그인 상태 관리 코드 정리
- [ ] axios 코드 수정
- [ ] localstorage에 jwt 토큰 넣기
- [ ] 유효성 검사 error message 코드 적기
- [ ] 모달 창 수정 & css 수정
